# Generated by Django 4.0.3 on 2022-04-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.CharField(max_length=200)),
                ('URL', models.CharField(max_length=50)),
                ('adTitle', models.CharField(max_length=50)),
                ('adInfo', models.CharField(max_length=200)),
            ],
        ),
    ]
