# Generated by Django 4.0.4 on 2022-04-15 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adDatabase', '0002_rename_image_ad_image_remove_ad_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='auto_increment_id',
            new_name='id',
        ),
    ]
